## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/lovely_korea?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    platform: mysql
    initialization-mode: always
    continue-on-error: true
  jpa:
    show-sql: false
    #    generate-ddl: false
    hibernate:
      ddl-auto: create
    database: mysql
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false;
    database-platform: org.hibernate.dialect.MySQL55Dialect
  #      dialect: org.hibernate.dialect.MySQL5Dialect

  #  jackson:
  #    default-property-inclusion: non_null
  #  redis:
  #    host: localhost
  #    port: 6379
  #  freemarker:
  #      cache: false




  queries:
    users-query: select email, password, active from users where email=?
    roles-query: select email, role from users where email=?
